version: '3.8'

services:
  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  postgres_data:

